/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function addProject(path: string): Project

export interface Beat {
  id: number
  name: string
  description: string
  archived: boolean
  createdAt: string
  costUsd: number
  promptTokens: number
  completionTokens: number
  projectId?: number
  projectName?: string
}

export declare function cancelCurrent(beatId: number): void

export declare function createBeat(name: string, description: string, projectId?: number | undefined | null): Beat

export declare function deleteBeat(id: number): string

export declare function discoverSkills(): Array<SkillInfo>

export declare function executeTool(name: string, arguments: string, cwd?: string | undefined | null): Promise<string>

export declare function getApiKey(provider: string): string | null

export declare function getBaseUrl(provider: string): string | null

export declare function getBeatMessages(id: number): Array<Record<string, unknown>>

export declare function getModelConfig(): ModelConfig

export declare function listBeats(): Array<Beat>

export declare function listModels(): Promise<Array<Model>>

export declare function listProjects(): Array<Project>

export interface Model {
  id: string
  name: string
  contextLength?: number
  pricingPrompt: string
  pricingCompletion: string
}

export interface ModelConfig {
  classifier: string
  high: string
  base: string
  low: string
}

export interface ModelUsage {
  model: string
  promptTokens: number
  completionTokens: number
  costUsd: number
}

export interface Project {
  id: number
  name: string
  path: string
  source: string
  createdAt: string
}

export declare function removeProject(id: number): void

/**
 * Run one task on the harness, streaming live events to `on_event`.
 * Each event carries the beat id so several sessions can run at once.
 */
export declare function runTask(beatId: number, prompt: string, images: Array<string>, onEvent: (ev: { beatId: number } & Record<string, unknown>) => void): Promise<TaskResult>

export declare function saveApiKey(provider: string, key: string): void

export declare function saveBaseUrl(provider: string, url: string): void

export declare function saveModelConfig(cfg: ModelConfig): void

export declare function setBeatArchived(id: number, archived: boolean): void

export interface SkillInfo {
  name: string
  description: string
  path: string
}

/** Refresh the cached model list every 15 minutes on a background thread. */
export declare function startModelsRefresh(): void

export declare function stripDiff(result: string): string

export interface TaskResult {
  tier: string
  model: string
  steps: Array<string>
  toolSteps: Array<ToolStep>
  answer: string
  usage: Array<ModelUsage>
  costUsd: number
  contextPercent?: number
  contextFull: boolean
  newBeatId?: number
}

export declare function toolDefinitions(): Array<any>

export interface ToolStep {
  tool: string
  arguments: string
  result: string
  error: boolean
}

export declare function unifiedDiff(before: string, after: string, maxLines: number): string

export interface UsageTotal {
  model: string
  promptTokens: number
  completionTokens: number
  costUsd: number
}

export declare function usageTotals(beatId: number): Array<UsageTotal>

export declare function workingDir(beatId: number): string | null
